config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get   '/home',    :to => 'static_pages#home'
  get   '/help',    :to => 'static_pages#help'
  get   '/about',   :to => 'static_pages#about'
  get   '/contact', :to => 'static_pages#contact'

  get       '/signup',  :to => 'users#new'
  post      '/signup',  :to => 'users#create'
  resources :users

  get     '/login',   :to => "sessions#new"
  post    '/login',   :to => "sessions#create"
  delete  '/logout',  :to => "sessions#destroy"

  resources :account_activations, :only => [:edit]

  resources :memes do
    member do
      patch   'tag'
      delete  'untag'
    end
  end

  resources :tags, :param => :slug do
    member do
      get 'memes/:meme_id', :to => "tags#show_meme"
    end
    collection do
      # support links already sent using tag IDs
      get ':id', :constraints => {  :id => /[0-9]*/ }, :to => redirect { |params|
        tag = Tag.find_by(:id => params[:id]) || ApplicationController::not_found!
        "/tags/#{tag.slug}"
      }
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>This should say something about the Memes Manager.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<% email = "playful.pachyderm@gmail.com" %>

<h1>Contact</h1>
<p>
	Contact Alessio by email: <%= email %>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>This is a help page, where you can find help about the Memes Manager.  I don't know how it works, so I have no idea how I'm supposed to help you. :(</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1>Memes Manager</h1>
    <h2>
        <p>This is the home page for the Memes Manager.</p>
        <p>
            This page is not very exciting.  Start browsing
            <%= link_to "MEMES", memes_path %>
            now!
        </p>
    </h2>

    <%= link_to "Sign up now!", signup_path, :class => "btn btn-lg btn-primary" %>
</div>


<div class="meme_icon">
    <%= link_to image_tag("icon.png", :alt => "Rails logo", :height => 300, :width => 300),
    			ApplicationHelper::THE_DONALD_URL %>
</div>