config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get   '/home',    :to => 'static_pages#home'
  get   '/help',    :to => 'static_pages#help'
  get   '/about',   :to => 'static_pages#about'
  get   '/contact', :to => 'static_pages#contact'

  get       '/signup',  :to => 'users#new'
  post      '/signup',  :to => 'users#create'
  resources :users

  get     '/login',   :to => "sessions#new"
  post    '/login',   :to => "sessions#create"
  delete  '/logout',  :to => "sessions#destroy"

  resources :account_activations, :only => [:edit]

  resources :memes do
    member do
      patch   'tag'
      delete  'untag'
    end
  end

  resources :tags, :param => :slug do
    member do
      get 'memes/:meme_id', :to => "tags#show_meme"
    end
    collection do
      # support links already sent using tag IDs
      get ':id', :constraints => {  :id => /[0-9]*/ }, :to => redirect { |params|
        tag = Tag.find_by(:id => params[:id]) || ApplicationController::not_found!
        "/tags/#{tag.slug}"
      }
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meme.rb
class Meme < ApplicationRecord
  # reference:
  # #http://guides.rubyonrails.org/association_basics.html#methods-added-by-has-and-belongs-to-many
  has_and_belongs_to_many :tags
  belongs_to :host

  default_scope -> { order(:id => :asc) }

  validate :ensure_valid_url
  validates :filename, :uniqueness => { :scope => :host }

  SLIMG_404 = File.read("app/assets/images/slimg_404.jpg")

  def tag_with(label, create: false)
    # ignore if already tagged with this tag
    return nil if tags.exists?(:name => label)

    tag = Tag.find_by(:name => label)
    if !tag
      if create
        tag = Tag.new(:name => label)
        tag.generate_slug
        tag.save
      else
        return nil
      end
    end

    self.tags << tag
    return tag
  end

  def untag(tag_id)
    tag = tags.find_by(:id => tag_id)
    if tag
      self.tags.destroy(tag)
      return tag
    else
      return nil
    end
  end

  def url
    if host
      return host.url + filename
    else
      return nil
    end
  end

  def self.find_next(num, increment)
    comparator = increment > 0 ? ">" : "<"
    order = increment > 0 ? :asc : :desc
    result = Meme.unscoped.where("id #{comparator} #{num}").order(:id => order).limit(1)
    return result.any? ? result[0].id : nil
  end

  def self.find_meme(filename)
    meme = Host.slimg.check_meme(filename)
    return meme if meme
    if !meme
      Host.not_slimg.each do |host|
        return meme if meme
        meme = host.check_meme(filename)
      end
    end
    return nil
  end

  private

    def ensure_valid_url
      begin
        code = HTTParty.get(url).code
      rescue
        errors.add(:url, "is not a proper URL")
      end

      if code != 200
        errors.add(:url, "could not be accessed properly (status: #{code})")
      end
    end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  before_action :ensure_logged_in
  before_action :ensure_admin_user, :except => [:show, :index]

  def new
    @meme = Meme.new(:filename => "fake filename")
  end

  def show
    @meme = Meme.find_by_id(params[:id]) or not_found!
    @new_tag = Tag.new
    if params[:bad_tag_name]
      @new_tag.name = params[:bad_tag_name]
      @new_tag.errors.add(:name, "does not exist")
    end
  end

  def create
    @meme = Host.match(params[:meme][:url])
    if @meme.save
      redirect_to meme_path(@meme)
    else
      render 'new'
    end
  end

  def untag
    @meme = Meme.find_by_id(params[:id])
    if @meme.untag(params[:tag_id])
      redirect_to base_referrer() || meme_path(@meme)
    else
      not_found!("No such tagging")
    end
  end

  def tag
    tag_name = params[:tag][:name]
    @meme = Meme.find_by_id(params[:id])
    if @meme.tag_with(tag_name)
      redirect_to base_referrer() || meme_path(@meme)
    else
      flash[:danger] = @meme.tags.exists?(:name => tag_name) ?
                    "Already tagged with that" : "Invalid tag name"
      if request.referrer
        redirect_to base_referrer({:bad_tag_name => tag_name})
      else
        redirect_to meme_path(@meme, :bad_tag_name => tag_name)
      end
    end
  end

  def update
  end

  def index
    @memes = Meme.paginate(:page => params[:page])
  end

  def destroy
    meme = Meme.find_by_id(params[:id])
    if meme
      meme.destroy
      flash[:success] = "Meme deleted"
    end
    redirect_to params[:redirect_path]
  end

  private

    def base_referrer(params_hash = nil)
      return nil if !request.referrer
      referrer = request.referrer.split("?")[0]
      if params_hash
        referrer += "?" + params_hash.to_query
      end
      return referrer
    end
end

app/helpers/memes_helper.rb
module MemesHelper
  def next_meme_path(tag, meme, increment)
    if tag
      next_num = tag.find_next(tag.find_index_of_meme(meme), increment)
      return next_num ? show_meme_path(tag, next_num) : nil
    else
      next_num = Meme.find_next(meme.id, increment)
      return next_num ? meme_path(next_num) : nil
    end
  end

  def meme_delete_redirect_path(tag, meme)
    return next_meme_path(tag, meme, tag ? 0 : 1)
  end
end

app/views/memes/_arrow.html.erb
<% href = next_meme_path(@tag, @meme, increment) %>
<% if href %>
  <% direction = increment > 0 ? "right" : "left" %>

  <a class="arrow-holder <%= direction %>" href="<%= href %>">
    <div class="arrow arrow-<%= direction %>"></div>
    </a>
<% end %>

app/views/memes/_memes_list.html.erb
<%= will_paginate memes %>

<ul id="memes_list">
	<% memes.each do |meme| %>
	  <li class="meme_thumb">
	    <%= link_to image_tag(meme.url), @tag ? show_meme_path(@tag, @tag.find_index_of_meme(meme))
	    																			: meme_path(meme) %>
	  </li>
	<% end %>
</ul>

<%= will_paginate memes %>

app/views/memes/_tag.html.erb
<li class="tag" data-id="<%= tag.id %>">
      <%= link_to tag.name, tag_path(tag) %>
      <% if current_user.admin? %>
        <%= form_tag(untag_meme_path(@meme), :method => :delete, :remote => false) do %>
          <%= hidden_field_tag :tag_id, tag.id %>
          <%= submit_tag "×", :class => "link-button" %>
        <% end %>
      <% end %>
    </li>

app/views/memes/index.html.erb
<%= render :partial => "memes_list", :locals => { :memes => @memes } %>

app/views/memes/new.html.erb
<%= form_for(@meme) do |f| %>
  <%= render :partial => 'shared/error_messages', :locals => { :form_object => @meme } %>
  <%= f.label :url %>
  <%= f.text_field :url, :class => "form-control" %>
  <%= f.submit "Create meme" %>
<% end %>

app/views/memes/show.html.erb
<div id="main-image">
  <%= render :partial => "memes/arrow", :locals => { :increment => -1} %>
  <%= link_to image_tag(@meme.url), @meme.url %>
  <%= render :partial => "memes/arrow", :locals => { :increment => 1} %>
</div>

<ul id="meme-tag-list">
  <li>tags:</li>
  <% @meme.tags.each do |tag| %>
    <!-- for unknown reasons, :locals won't work unless you use :partial as well -->
    <%= render :partial => "memes/tag", :locals => { :tag => tag } %>
  <% end %>

  <% if current_user.admin? %>
    <li class="tag-adder">
      <%= form_for(@new_tag, :url => tag_meme_path(@meme), :method => :patch) do |f| %>
        <%= f.text_field :name, :class => "_form-control" %>
        <%= f.submit "Add tag", :disable_with => "PLease WAIT!!!!lels" %>
      <% end %>
    </li>

    <li class="delete-meme">
      <%= form_tag(meme_path(@meme), :method => :delete) do %>
        <%= hidden_field_tag :redirect_path, meme_delete_redirect_path(@tag, @meme) %>
        <%= submit_tag "Delete", :data => { :confirm => "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/memes/tag.js.erb
<% if @tag %>
  var tags_list = document.querySelector(".tags");
  tags_list.innerHTML += "<%= render :partial => 'tag', :locals => { :tag => @tag } %>"
/*
  // var new_tag = document.createElement("li");
  // new_tag.setAttribute("class", "tag");
  // new_tag.setAttribute("data-id", "<%= @tag.id %>");

  // var link_to_tag = document.createElement("a");
  // link_to_tag.setAttribute("href", "<%= tag_path(@tag) %>");
  // link_to_tag.textContent = "<%= @tag.name %>";
  // new_tag.appendChild(link_to_tag);

  // var x_button = document.createElement("a");
  // x_button.setAttribute("href", "<%= untag_meme_path(@meme, @tag) %>");
  // x_button.setAttribute("data-remote", "true");
  // x_button.setAttribute("rel", "nofollow");
  // x_button.setAttribute("data-method", "delete");
  // x_button.textContent = "×";
  // new_tag.appendChild(x_button);

  // tags_list.appendChild(new_tag);
*/
  var input_box = document.querySelector("#tag_name")
  input_box.value = ""
<% else %>
  alert("Already tagged with that.");
<% end %>

app/views/memes/untag.js.erb
var node = document.querySelector(".tag[data-id='<%= @tag.id %>']")
node.parentNode.removeChild(node)