config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get   '/home',    :to => 'static_pages#home'
  get   '/help',    :to => 'static_pages#help'
  get   '/about',   :to => 'static_pages#about'
  get   '/contact', :to => 'static_pages#contact'

  get       '/signup',  :to => 'users#new'
  post      '/signup',  :to => 'users#create'
  resources :users

  get     '/login',   :to => "sessions#new"
  post    '/login',   :to => "sessions#create"
  delete  '/logout',  :to => "sessions#destroy"

  resources :account_activations, :only => [:edit]

  resources :memes do
    member do
      patch   'tag'
      delete  'untag'
    end
  end

  resources :tags, :param => :slug do
    member do
      get 'memes/:meme_id', :to => "tags#show_meme"
    end
    collection do
      # support links already sent using tag IDs
      get ':id', :constraints => {  :id => /[0-9]*/ }, :to => redirect { |params|
        tag = Tag.find_by(:id => params[:id]) || ApplicationController::not_found!
        "/tags/#{tag.slug}"
      }
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Memes Manager, courtesy of Alessio Magnus, disciple of Jostaphius the Sun God
    </small>
    <nav>
        <ul>
            <li><%= link_to "About",    about_path %></li>
            <li><%= link_to "Contact",  contact_path  %></li>
            <li><%= link_to "News",     ApplicationHelper::THE_DONALD_URL %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Memes Manager", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? && current_user.admin? %>
              <li><%= link_to "New tag", new_tag_path, :id => "new-tag-button" %></li>
              <li><%= link_to "New meme", new_meme_path, :id => "new-meme-button" %></li>
            <% end %>
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Help",   help_path %></li>

            <% if logged_in? %>
                <li><%= link_to "Users", users_path %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Browse <div class="caret"></div>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Memes", memes_path %></li>
                    <li><%= link_to "Tags", tags_path %></li>
                  </ul>
                </li>

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", user_path(current_user) %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li class="divider" />
                    <li><%= link_to "Log out", logout_path,
                          :method => :delete %></li>
                  </ul>
                </li>
            <% else %>
                <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |msg_type, msg| %>
        <div class="alert alert-<%= msg_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>